### ISSUE TITLE
observations during the update of the opensuse package

### ISSUE THREAD

**Issue by darix** [PortMidi/portmidi#13]
1. the jni library needed for pmdefaults doesnt like alsa on linux. `PM_NEEDED_LIBS` seems to be only used in the cmake file for jni but  never filled. should we ship the java parts at all?

2. in the past we installed and packaged portmidi-latency portmidi-mm portmidi-midiclock portmidi-midithread portmidi-midithru portmidi-sysex portmidi-test portmidi-qtest  ... those seem no longer be build or installed. should we just skip those?
3. in the past you had a libporttime which is gone now. I assume it was merged into libportmidi?

**Comment by rbdannenberg** [comment]
Darn. PM_NEEDED_LIBS was meant to list library dependencies, but things were reorganized since CMake now allows dependencies to be attached to libraries, e.g., since test programs depend on portmidi and portmidi depends on alsa, we no longer have to set PM_NEEDED_LIBS to pthread;asound and explicitly link test programs with PM_NEEDED_LIBS. Unfortunately, this did not work with pmjni, but my "tests" worked because I still had PM_NEEDED_LIBS defined in my CMakeCache.txt file. So much for my testing procedures. I'll have to fix this.

2. All the test programs can be compiled by setting the option BUILD_PORTMIDI_TESTS. It would be nice to package at least portmidi-mm -- it's a useful Midi monitor program. The next most important one is portmidi-testio (renamed because "test" was just too generic) which allows you to see what devices you have and send or receive some simple MIDI. The rest are used for testing PortMidi and provide some example code, but not something a user would likely need otherwise.

3. Yes libporttime is merged into portmidi -- I don't know of anyone using it separately. Similarly, portmidi and porttime are duplicated in pmjni so Java programs only have to deal with one external library.

**Comment by Be-ing** [comment]
> should we ship the java parts at all?

As a user, I certainly do *not* want to install Java to install a C/C++ application with a dependency on PortMidi.

**Comment by rbdannenberg** [comment]
> 1. should we ship the java parts at all?

I consider the Java and PmDefaults code mainly useful for people writing their own command line code, since it enables them to actually set preferred devices for their system. I agree with Be that if you're using/installing an application that already manages its own preferences, it would be annoying to install Java for no benefit.

**Comment by rbdannenberg** [comment]
The most recent push should resolve the pmjni and PM_NEEDED_LIBS problem -- whether the option is used or not. This will become v2.0.2 on Monday (also updates some macOS configuration stuff) unless there's more to change by then.

**Comment by darix** [comment]
current package can be seen [here][0]

make install doesnt install the jar file and the startup script and the startup script now says that it should be started from the build working copy. I didnt test the java part. 

[0]: https://build.opensuse.org/package/show/home:darix:branches:multimedia:libs/portmidi

**Comment by rbdannenberg** [comment]
Thanks - just updated the CMake version. 

Yes, PmDefaults works in a limited way, but I don't know how to install Java programs, much less to extend System Preferences on Win/macOS/Linux. If no one expresses interest in actually using PmDefaults, Pm_DefaultInputDevice(), and Pm_DefaultOutputDevice(), then they'll probably be removed in about a year. I use them occasionally, but there are alternative ways to achieve the same goals, and simpler is probably better.

**Comment by darix** [comment]
package updated
