### ISSUE TITLE
handling hot plugged devices

### ISSUE THREAD

**Issue by mrf-r** [PortMidi/portmidi#63]
Hello!
When disconnecting or connecting (USB) devices during operation (after **Pm_Initialize()**), the value returned by **Pm_CountDevices()** does not change. **Pm_Read()** also does not return any errors.
Is this a limitation or a bug?
Is it possible to implement this functionality in future versions? Could you please suggest a way to track changes in hardware configuration at runtime? 
Tested on Windows11(MinGW-w64) and Ubuntu

**Comment by rbdannenberg** [comment]
This is a limitation, not a bug. Scanning for devices is not a particularly real-time operation and on some systems I think it requires another thread (and be careful with that because PortMidi is not only single-threaded but if you poll PortMidi at a raised priority, there would be priority inversion problems interacting with a lower-priority thread, which is why PortMidi passes data through a lock-free queue.) My solution is a menu selection to explicitly rescan devices. This shuts down and reinitializes PortMidi. While shut down, application calls to poll for MIDI or send MIDI have to be intercepted since devices are closed. After reinitializing, device numbers may change, but I search for and reconnect devices based on names. All of this operates in a fairly small abstraction layer above the PortMidi API. This is all implemented in my language Serpent and ties into both a Preferences library and a Menu system, so it would not make sense to put it in PortMidi. I'm happy to share the code.

**Comment by mrf-r** [comment]
So there is no way for the program to know that used device has become unplugged?

**Comment by rbdannenberg** [comment]
Not from within PortMidi. For any given system (Win32, MacOS, Linux), you can write your own code to detect unplugged or newly plugged devices in a way that's consistent with your requirements. If you need access to hidden data in PortMidi, I would see that as a priority for PortMidi supports, and maybe we could make some additional code for monitoring device status available outside the core PortMidi library.

**Comment by mrf-r** [comment]
Ok, I see. Thanks for the answers, Roger! I looked at other libraries and it seems like this is common behavior. I'll try to find a more reliable USB cable)
